pythonproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('webpage/',include('webpage.urls',namespace='webpage')),
]

urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

webpage/urls.py
from django.urls import path
from . import views
app_name='webpage'
urlpatterns = [
    path('about_us/',views.about,name='about'),
    path('gallery/',views.gallery,name='gallery'),
    path('service/',views.service,name='service'),
    path('features/',views.features,name='features'),
    path('login/',views.login_page,name='login_page'),
    path('register/',views.signup_page,name='signup_page'),
    path('detail/',views.detail,name='detail'),
    path('logout/',views.logout_page,name="logout"),
]

templateshape/models.py
from django.db import models

# Create your models here.

webpage/models.py
from django.db import models

# Create your models here.

pythonproject/views.py
from django.shortcuts import render,redirect


def home(request):
    text=''
    if(request.user.is_authenticated==True):
        text='Logout'
    else:
        text="Login"
    print(text)    
    return render(request,'home.htm',{'text':text})

templateshape/views.py
from django.shortcuts import render

# Create your views here.

webpage/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


def about(request):
    text=''
    if(request.user.is_authenticated==True):
        text='Logout'
    else:
        text='Login'
    return render(request,'webpage/about-us.htm',{'text':text})

def gallery(request):
    text=''
    if(request.user.is_authenticated==True):
        text='Logout'
    else:
        text='Login'
    return render(request,'webpage/gallery.htm',{'text':text})


def service(request):
    text=''
    if(request.user.is_authenticated==True):
        text='Logout'
    else:
        text='Login'
    return render(request,'webpage/services.htm',{'text':text})


def features(request):
    text=''
    if(request.user.is_authenticated==True):
        text='Logout'
    else:
        text='Login'
    return render(request,'webpage/components.htm',{'text':text})


def login_page(request):
    form=AuthenticationForm()
    if(request.method=='POST'):
        form= AuthenticationForm(data=request.POST)
        if(form.is_valid()):
            user=form.get_user()
            login(request,user)
            return redirect('webpage:detail')

    return render(request,'webpage/login.html',{'form':form})

def signup_page(request):
    form= UserCreationForm()
    if(request.method=='POST'):
        form= UserCreationForm(request.POST)
        if(form.is_valid()):
            user=form.save()
            login(request,user)
            return redirect('webpage:detail')
    return render(request,'webpage/signup.html',{'form':form})

def detail(request):
    x=request.user.is_authenticated
    print(x)
    text=''
    if(request.user.is_authenticated==True):
        text='Logout'
        return render(request,'webpage/blog-detail.htm',{'text':text})
    else:
        text='Login'
    return render(request,'home.htm',{'text':text})


# def logout_page(request):
#
#     if(request.method=='POST'):
#         logout(request)
#     return render(request,'home.htm')

def logout_page(request):
    text=''
    if(request.user.is_authenticated==True):
        logout(request)
        text='Login'
        return render(request,'home.htm',{'text':text})
    elif(request.user.is_authenticated==False):
        text='Logout'
        return redirect('webpage:login_page')

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="not-ie" lang="en"> <!--<![endif]-->
<head>
	<!-- Basic Meta Tags -->
  <meta charset="utf-8">
  <title>Ucorpora Demo</title>
	<meta name="description" content="ucorpora demo - Free Business Corporate HTML Template">
	<meta name="keywords" content="ucorpora, ucorpora demo, free, template, corporate, clean, modern, bootstrap, creative, design">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--[if (gte IE 9)|!(IE)]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <![endif]-->

  <!-- Favicon -->
  <link href="{% static 'templateshape/img/favicon.ico' %}" rel="icon" type="image/png">

  <!-- Styles -->
  <link href="{% static 'templateshape/css/styles.css' %}" rel="stylesheet">
  <link href="{% static 'templateshape/css/bootstrap-override.css' %}" rel="stylesheet">

  <!-- Font Avesome Styles -->
  <link href="{% static 'templateshape/css/font-awesome/font-awesome.css' %}" rel="stylesheet">
	<!--[if IE 7]>
		<link href="css/font-awesome/font-awesome-ie7.min.css" rel="stylesheet">
	<![endif]-->

  <!-- FlexSlider Style -->
  <link rel="stylesheet" href="{% static 'templateshape/css/flexslider.css' %}" type="text/css" media="screen">

	<!-- Internet Explorer condition - HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

</head>
<body>
  <!-- Header -->
  <header id="header">
    <div class="container">
      <div class="row t-container">

        <!-- Logo -->
        <div class="span3">
          <div class="logo">
            <a href="index.htm"><img src="{% static 'templateshape/img/logo-header.png' %}" alt=""></a>
          </div>
        </div>

        <div class="span9">
          <div class="row space60"></div>
             <nav id="nav" role="navigation">
               	<a href="#nav" title="Show navigation">Show navigation</a>
	            <a href="#" title="Hide navigation">Hide navigation</a>
	            <ul class="clearfix">
	           	<li class="active"><a href="{% url 'home' %}" title="">Home</a></li>
                <li><a href="{% url 'webpage:about' %}" title="">About Us</a></li>
                <li><a href="{% url 'webpage:gallery' %}" title="">Gallery</a></li>
                <li><a href="{% url 'webpage:service' %}" title="">Services</a></li>
                <li><a href="{% url 'webpage:features' %}" title="">Features</a></li>
                <!-- <li><a href="{% url 'webpage:login_page' %}" title="">Login to other details </a></li> -->
                <li><a href="{% url 'webpage:signup_page' %}" title="">signup</a></li>
                <!-- <li><a href="{% url 'webpage:logout' %}" title="">logout</a></li> -->
                <li><form action="{% url 'webpage:logout' %}" method="POST">{% csrf_token %}<input type="submit" class="btn btn-link" value="{{text}}"/></form></li>

  			      <!-- <ul>
                      <li><a href="components.htm" title="">Components</a></li>
                      <li><a href="blog.htm" title="">Blog</a></li>
                      <li><a href="blog-detail.htm" title="">Blog Detail</a></li>
                      <li><a href="contact.htm" title="">Contact</a></li>
  		         </ul>
               </li>
	           </ul> -->
          </nav>
         </div>
      </div>

{% block content %}{% endblock %}


<!-- Footer -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="span5">
      <h3>Contact Form</h3>
      <div>
        <form class="form-main" name="ajax-form" id="ajax-form" action="#" method="post">
          <div id="ajaxsuccess">E-mail was successfully sent.</div>
          <div class="error" id="err-name">Please enter name</div>
          <input name="name" id="name" type="text" value="Name" onfocus="if(this.value == 'Name') this.value='';" onblur="if(this.value == '') this.value='Name';">

          <div class="error" id="err-email">Please enter e-mail</div>
          <div class="error" id="err-emailvld">E-mail is not a valid format</div>
          <input  name="email" id="email" type="text" value="E-mail" onfocus="if(this.value == 'E-mail') this.value='';" onblur="if(this.value == '') this.value='E-mail';">

          <div class="error" id="err-message">Please enter message</div>
          <textarea  name="message" id="message" onfocus="if(this.value == 'Message') this.value='';" onblur="if(this.value == '') this.value='Message';">Message</textarea><br>
          <div>
            <div class="error" id="err-form">There was a problem validating the form please check!</div>
            <div class="error" id="err-timedout">The connection to the server timed out!</div>
            <div class="error" id="err-state"></div>
          </div>
          <button id="send" class="btn f-right">Send Message <i class="icon-ok"></i></button>
        </form>
      </div>
      </div>
      <div class="span3 offset3">
        <h3>Address</h3>
        81 Sunnyvale Street<br>
        Los Angeles, CA 90185<br>
        United States<br>
        <br>
        <i class="icon-phone"></i>+01 880 555 999<br>
        <i class="icon-envelope"></i><a href="mailto:support@example.com">support@example.com</a><br>
        <i class="icon-home"></i><a href="#">www.example.com</a>

        <div class="row space40"></div>

        <a href="#" class="social-network sn2 behance"></a>
        <a href="#" class="social-network sn2 facebook"></a>
        <a href="#" class="social-network sn2 pinterest"></a>
        <a href="#" class="social-network sn2 flickr"></a>
        <a href="#" class="social-network sn2 dribbble"></a>
        <a href="#" class="social-network sn2 lastfm"></a>
        <a href="#" class="social-network sn2 forrst"></a>
        <a href="#" class="social-network sn2 xing"></a>
      </div>
    </div>

    <div class="row space50"></div>
    <div class="row">
      <div class="span6">
        <div class="logo-footer">
          Design by <a href="https://www.freshdesignweb.com">freshDesignweb</a>
        </div>
      </div>
      <div class="span6 right">
        &copy; 2020. All rights reserved.
      </div>
    </div>

  </div>
</footer>
<!-- Footer End -->

<!-- JavaScripts -->
<script type="text/javascript" src="{% static 'templateshape/js/jquery-1.8.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'templateshape/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'templateshape/js/functions.js' %}"></script>
<script type="text/javascript" defer src="{% static 'templateshape/js/jquery.flexslider.js' %}"></script>

</body>
</html>

templates/home.htm
{% extends 'base.html' %}
{% load static %}
{% block content %}
       <div class="row space40"></div>
          <div class="slider1 flexslider">  <!-- Slider -->
            <ul class="slides">
              <li>
    	    	    <img src="{% static 'templateshape/img/slider/1.jpg' %}" alt="">
    	    		</li>
    	    		<li>
    	    	    <img src={% static 'templateshape/"img/slider/2.jpg' %}" alt="">
    	    		</li>
    	    		<li>
    	    	    <img src="{% static 'templateshape/img/slider/3.jpg' %}" alt="">
    	    		</li>
                    <li>
    	    	    <img src="{% static 'templateshape/img/slider/4.jpg' %}" alt="">
    	    		</li>
            </ul>
          </div>  <!-- Slider End -->
  </div>
</header>
  <!-- Header End -->
  <!-- Content -->
  <div id="content">
    <div class="container">
       <div class="f-center">
              <h2>why choose us ?</h2>
              <div class="head-info">
                Magna in pulvinar tempor montes pulvinar habitasse parturient? Elementum facilisis sit et, dolor placerat, turpis auctor. Lundium ultricies augue urna arcu aliquet velit?
            </div>
       </div>
       <div class="f-hr"></div>
      <div class="row space40"></div>
      <div class="row">
        <div class="span12">
          <div class="row">
            <!-- Service Container -->
            <div class="span4">
              <!-- Service Icon -->
              <div class="ic-1"><i class="icon-lightbulb"></i></div>
              <!-- Service Title -->
              <div class="title-1"><h4>Powerful clean design</h4></div>
              <!-- Service Content -->
              <div class="text-1">
                On sait depuis longake apple pie. Gingerbread cotton candy icing ice cream applicake wafetemps nnaire de plus de 200 mots pluskan rlatin
              </div>
            </div>
            <!-- Service Container End -->
            <div class="span4">
              <div class="ic-1"><i class="icon-resize-small"></i></div>
              <div class="title-1"><h4>Fully responsive</h4></div>
              <div class="text-1">
                Iil utilise un dictionnaire de plus de 200 mots kan rlarem as Ipsumtiotins, en combiake apple pie. Gingerbread icing ice cream applicake wafenaison.
              </div>
            </div>
            <div class="span4">
              <div class="ic-1"><i class="icon-eye-open"></i></div>
              <div class="title-1"><h4>Retina Ready</h4></div>
              <div class="text-1">
                Contrairement à une opinion répandue, Lorem as Ipsumtionnaire de plus n'est pas simplake apple pie. Gingerbread cotton  ice cream applicake wafeement.
              </div>
            </div>
          </div>
        </div>

        <div class="span12">
          <h2>We have provide best consulting service</h2>
        </div>
        <div class="span8">
          <img src="{% static 'templateshape/img/image01.png' %}" alt="">
        </div>
        <div class="span4">
          <div class="ic-1"></div>
          <div class="title-1"><h4>Our Service:</h4></div>
          <!-- List -->
          <div class="text-1">
            <ul class="list-b">
              <!-- List Items -->
              <li><i class="icon-ok"></i> Tax Consulting.</li>
              <li><i class="icon-ok"></i> Business Consulting.</li>
              <li><i class="icon-ok"></i> Data analysis methods.</li>
              <li><i class="icon-ok"></i> On demand consulting.</li>
              <li><i class="icon-ok"></i> Private consultant.</li>
            </ul>
          </div>
          <!-- List End -->
        </div>

      </div>

      <div class="space40"></div>

      <!-- Our Clients -->
      <div class="row">
        <div class="span12">
          <h3>Our Clients</h3>
        </div>
      </div>

      <div id="our-clients" class="slider2 flexslider">
        <ul class="slides">
          <li>
            <div class="row">
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/1.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/2.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/3.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/4.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/5.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/6.png' %}" alt="">
                </a>
              </div>
            </div>
          </li>
          <li>
            <div class="row">
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/4.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/3.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/1.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/2.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/5.png' %}" alt="">
                </a>
              </div>
              <div class="span2">
                <a href="#" rel="external">
                    <img src="{% static 'templateshape/img/our-clients/6.png' %}" alt="">
                </a>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <!-- Our Clients End -->

      <div class="space50"></div>

    </div>
  </div>
  {% endblock %}
  <!-- Content End -->

webpage/templates/webpage/about-us.htm
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="titlebar">
	<!-- Container -->
	<div class="container">

		<div class="eight columns">
			<h3 class="left">About</h3>
		</div>

		<div class="eight columns">
			<nav id="breadcrumbs">
				<ul>
					<li>You are here:</li>
					<li><a href="{% url 'home' %}">Home</a></li>
					<li>About</li>
				</ul>
			</nav>
		</div>

	</div>
	<!-- Container / End -->
</section>

  <!-- Content -->
  <div id="content">
    <div class="container">

      <div class="row">
        <div class="span12">
          <h4>Who We Are?</h4>
          <p>Ucorpora ut molestie turpis, elementum tempor metus. Vestibulum non nibh porttitor, eleifend purus eu, pulvinar orci. Quisque a gravida lorem, eu lobortis magna. Nulla auctor urna quis facilisis pretium. Cras facilisis risus sed mauris gravida, id vestibulum erat dictum. Nam in ante massa. Integer ultricies libero lorem, egestas dictum augue aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis.</p>

<p>Elementum tempor metus donec ut molestie turpis. Vestibulum non nibh porttitor, eleifend purus eu, pulvinar orci. Quisque a gravida lorem, eu lobortis magna. Nulla auctor urna quis facilisis pretium. Cras facilisis risus sed mauris gravida, id vestibulum erat dictum. Nam in ante massa. Integer ultricies libero lorem.</p>
          <!-- Our Team -->
          <h3>Our Team</h3>

          <div  class="slider2 team flexslider">
            <ul class="slides">
              <li>
                <div class="row">

                  <a href="#">
                    <div class="span3 square-1">
                      <div class="img-container">
                        <img src="{% static 'templateshape/img/our-team/1.jpg' %}" alt="">
                        <div class="img-bg-icon"></div>
                      </div>
                      <h4>John Smith</h4>
                        managing director
                    </div>
                  </a>

                  <a href="#">
                    <div class="span3 square-1">
                      <div class="img-container">
                        <img src="{% static 'templateshape/img/our-team/2.jpg' %}" alt="">
                        <div class="img-bg-icon"></div>
                      </div>
                      <h4>Jokey Holid</h4>
                        designer
                    </div>
                  </a>

                  <a href="#">
                    <div class="span3 square-1">
                      <div class="img-container">
                        <img src="{% static 'templateshape/img/our-team/3.jpg' %}" alt="">
                        <div class="img-bg-icon"></div>
                      </div>
                      <h4>Graham Bill</h4>
                        project manager
                    </div>
                  </a>

                  <a href="#">
                    <div class="span3 square-1">
                      <div class="img-container">
                        <img src="{% static 'templateshape/img/our-team/4.jpg' %}" alt="">
                        <div class="img-bg-icon"></div>
                      </div>
                      <h4>Kenny Delak </h4>
                        developer
                    </div>
                  </a>

                </div>
              </li>
              <li>
                <div class="row">

                  <a href="#">
                    <div class="span3 square-1">
                      <div class="img-container">
                        <img src="{% static 'templateshape/img/our-team/3.jpg' %}" alt="">
                        <div class="img-bg-icon"></div>
                      </div>
                      <h4>Joe Ganesha</h4>
                        founder
                    </div>
                  </a>

                  <a href="#">
                    <div class="span3 square-1">
                      <div class="img-container">
                        <img src="{% static 'templateshape/img/our-team/4.jpg' %}" alt="">
                        <div class="img-bg-icon"></div>
                      </div>
                      <h4>Mario Balio</h4>
                        programmer
                    </div>
                  </a>

                  <a href="#">
                    <div class="span3 square-1">
                      <div class="img-container">
                        <img src="{% static 'templateshape/img/our-team/1.jpg' %}" alt="">
                        <div class="img-bg-icon"></div>
                      </div>
                      <h4>Jane Buckler</h4>
                        junior designer
                    </div>
                  </a>

                  <a href="#">
                    <div class="span3 square-1">
                      <div class="img-container">
                        <img src="{% static 'templateshape/img/our-team/2.jpg' %}" alt="">
                        <div class="img-bg-icon"></div>
                      </div>
                      <h4>Zeda Junar</h4>
                        analyst
                    </div>
                  </a>

                </div>
              </li>
            </ul>
          </div>
          <!-- Our Team End -->

          <!-- Typography Row -->
          <div class="row t-row">
            <!-- Line -->
            <div class="span12"><hr></div>
            <div class="span9">
              <h2>We have become the fastest growing</h2>
            </div>
            <div class="span3">
              <!-- Button -->
              <div class="btn btn-blue f-right">
                <!-- Title -->
                <h3><i class="icon-signin hidden-tablet"></i> More Info</h3>
              </div>
            </div>
            <div class="space30 visible-phone"></div>
            <!-- Line -->
            <div class="span12"><hr></div>
          </div>
          <!-- Typography Row End-->

          <div class="row space10"></div>

          <div class="row">
            <!-- List -->
            <div class="span4">
              <h3>List</h3>
              <ul class="list-a">
                <li>Le Aorem Ipsum ainsi obtenu ne seeng elit.</li>
                <li>Contrairement à Lorem n'est aliquet mollis.</li>
                <li>On sait depuis travailler cotà une opinion.</li>
                <li>Al contrario di quaon enodio, quis fringilla.</li>
                <li>Sopravvissuto non solo velor iaculis.</li>
                <li>Sait depuis longtendue gravida porttitor.</li>
              </ul>
            </div>
            <!-- List End -->

            <!-- Progress Bar -->
            <div class="span4">
              <h3>Progress Bar</h3>
              <div class="progress">
                <div class="bar" style="width: 73%;">HTML/CSS 73%</div>
              </div>
              <div class="progress">
                <div class="bar" style="width: 100%;">Web Design 100%</div>
              </div>
              <div class="progress">
                <div class="bar" style="width: 78%;">Photography 78%</div>
              </div>
              <div class="progress">
                <div class="bar" style="width: 80%;">Sound Design 80%</div>
              </div>
              <div class="progress">
                <div class="bar" style="width: 63%;">Party 63%</div>
              </div>
            </div>
            <!-- Progress Bar End -->

            <!-- Client Says -->
            <div class="span4">
              <h3>Client Says</h3>
              <div class="client-says">
                “Claritas est etiam processus dynamicus, qui sur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas. Aliquam at erat in purus aliquet mollis. Fusce elementum velit vel dolor iaculis egestas. posuere vel vitae  elementum velit nibh.”
              </div>
              <div class="client-says-2">
                <div class="quotes">
                  <i class="icon-quote-right"></i>John Doe, Everton Inc.
                </div>
              </div>
            </div>
            <!-- Client Says End -->
          </div>

          <div class="row space50"></div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
  <!-- Content End -->

webpage/templates/webpage/login.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'templateshape/css/bootstrap.min.css' %}"/>
<h1>Login page </h1>

<form action="{% url 'webpage:login_page' %}" method="POST" class="form-control">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="Login Page"/>
</form>

webpage/templates/webpage/logout.html
<form action="{% url 'home' %}" method="POST">
  {% csrf_token %}
  <input type="submit"/>
</form>

webpage/templates/webpage/signup.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'templateshape/css/bootstrap.min.css' %}"/>
<h1>Signup Page </h1>
<form action="{% url 'webpage:signup_page' %}" method="POST" class="form-group,align">
  {% csrf_token %}

  {{form}}

  <input type="submit" value="Register"/>

</form>